# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-discovery',
                'doc_host': 'https://durjoi.github.io',
                'git_url': 'https://github.com/durjoi/nbdev-discovery',
                'lib_path': 'nbdev_discovery'},
  'syms': {'nbdev_discovery.core': {'nbdev_discovery.core.foo': ('core.html#foo', 'nbdev_discovery/core.py')}}}
